### ISSUE TITLE
Tasks for fully qualified name

### ISSUE THREAD

**Issue by shyamnamboodiripad** [microsoft/vstest#2833]
Spec:

- [x] 1. Publish helper API to generate compliant class and method names that adhere to the standard specified in  [0017-Managed-TestCase-Properties.md](https://github.com/microsoft/vstest-docs/blob/master/RFCs/0017-Managed-TestCase-Properties.md) (Related PRs: #2611, #2714)

- [x] 2. Publish helper API to standardize `TestCase.Id` generation (Related PRs: #2854)
- Adapters should be able to call this API and get back a deterministic and unique Id Guid given the same set of inputs (strings).
- Inputs would include the same method and class names returned by the API in #2 above. For parameterized tests, the inputs would also include argument values (which could be any value that can appear in a .NET attribute).

- [x] 3. Publish helper API to standardize test hierarchy display information (Related PRs: #2724, #2854)
- This can be accomplished by adding an `out` parameter on the API in 1 above that returns an array with default display name values for each level in the hierarchy (namespace, class, test group, and test).
- When creating Testcase objects, Test Adapter authors can choose to supply different values than what is returned in the `out` parameter) for any level, based on their own display name rules. However, having the `out` parameter on the above API would make the hierarchy functionality easier to discover (we could hang documentation comment on it) and would also avoid code duplication/parsing for computing the levels of the hierarchy that typically have fixed names that the end-user can’t change (such as for namespace and class). 

- [x] 4. Update guidance for test adapter authors (Related PRs: https://github.com/microsoft/vstest-docs/pull/247)
- Update [0017-Managed-TestCase-Properties.md](https://github.com/microsoft/vstest-docs/blob/master/RFCs/0017-Managed-TestCase-Properties.md) to include recent updates (including changes around how the test hierarchy will be encoded, how names with special Unicode characters will be handled etc.). 
- Understand whether it is possible to encounter names with special Unicode characters in the Roslyn symbol API. Our current assumption is that this should not be possible for source symbols (since such names are not legal in C#) however they may be encountered in metadata symbols from referenced F# assemblies. (Preliminary investigation did reveal that C# cannot interop with methods and classes containing special Unicode characters in their name.)

**Comment by shyamnamboodiripad** [comment]
FYI @peterwald @Haplois @pavelhorak

**Comment by Haplois** [comment]
Added https://github.com/microsoft/vstest-docs/pull/247 to update [0017-Managed-TestCase-Properties.md](https://github.com/microsoft/vstest-docs/blob/master/RFCs/0017-Managed-TestCase-Properties.md).
