### ISSUE TITLE
Visual Studio Test Explorer backlog

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#676]
## Visual Studio Test Explorer backlog
This backlog captures the focus of our upcoming work on the Visual Studio Test Explorer.
Please considering voting on the individual issues below.

- [ ] Accessibility drive
- [ ] Perfwatson issues
- [ ] Multi TFM support: [#298](https://github.com/Microsoft/vstest/issues/298), [#624](https://github.com/Microsoft/vstest/issues/624)
- [ ] Improved DPL integration: [#674](https://github.com/Microsoft/vstest/issues/674)
- [ ] Make playlist extensible: [#675](https://github.com/Microsoft/vstest/issues/675)
- [ ] Devices support refactored out: [#684](https://github.com/Microsoft/vstest/issues/684)
- [ ] Speed up test discovery performance leveraging test source information in the IDE: [#485](https://github.com/Microsoft/vstest/issues/485)
- [ ] Scale discovery perf. for large solutions: [#674](https://github.com/Microsoft/vstest/issues/674)
- [ ] Make Test Discovery parallel by default: [#499](https://github.com/Microsoft/vstest/issues/499)
- [ ] Test Explorer improvements: [#725](https://github.com/Microsoft/vstest/issues/725)
- [ ] Improve search ( filtering) experience  by adding support for wildcards etc - see  https://www.reddit.com/r/cpp/comments/6t0xa8/getting_started_with_c_unit_testing/

**Comment by abpiskunov** [comment]
Specifically for dotnet core projects, initial test discovery, i.e. when you opened a solution is very slow. It cam take minutes for tests to start slowly to appear in the window. Refresh after build is also slower than for classic csproj projects.

**Comment by davidfowl** [comment]
@pvlakshm Is that list in priority order?

**Comment by ManishJayaswal** [comment]
@pvlakshm - can you please add LUT integration for showing Live Test Set to the list as well?

**Comment by pvlakshm** [comment]
Closing this; we will not be tracking an all-up TestExplorer backlog here anymore. Individual issues on the Test Explorer are being tracked via VSFeedback.

**Comment by davidfowl** [comment]
Does it include the issues called out here?

**Comment by PureKrome** [comment]
Bummer that this GH repo will not be used for issues vs VSFeedback ... which is just Connect version 2 .... which is really just a first call, dumping ground for people to post their problems.

Would be really nice to keep this GH repo active with issues _from_ Connect that will have actions taken. Basically, a really laser focused filter of the Connect noise.
