### ISSUE TITLE
Devices support in vstest

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#684]
## Description

- Author a test in VS IDE, be able to deploy and run it on device, and view the outcome in the Test Explorer.
- Author a test in VS IDE, be able to deploy and debug it on device.
- Author a test, be able to deploy and run it on device using the command line, and view the outcome on the command line.
- Deployment to device, and launching the tests on device, must be realized using extensibility points on vstest. This will allow any device/platform (UWP, UWP/IoT, Android, etc.) to plug in into vstest and use its capabilities).

**Comment by sbaid** [comment]
### UWP Unit Testing support
#### Components
These are the components involved
1. [UWP Unit Testing Template](https://github.com/Microsoft/testfx/tree/master/Templates/UWP/ProjectTemplates/CSharp/Windows%20UAP)
2. UWP runtime provider that implement [ITestRuntimeProvider](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Host/ITestRunTimeProvider.cs)
3. UWP App Host - UWP app which hosts the UWP tests 
4. Unit Test Engine - Unit testing engine that gets loaded in the UWP Host process & provide core services.
5. Test Framework/Test Adapter - Unit testing framework extensions that enable unit testing engine to execute fx tests.
6. Vstest.console - CLI test runner
7. Test Explorer - Visual Studio IDE test runner

#### Scenarios
1. IDE - Create UWP UT project. Add reference to other UWP projects (as required). Build. Tests are discovered in Test Explorer and can be run/debug targeting
 a. Local machine
 b. An installed emulator
 c. Device [attached locally]
 d. [Remote machine](https://developer.microsoft.com/en-us/windows/iot/docs/appdeployment)
2. Vstest.console UwpUTProject.appx

#### Tasks
Here are the changes required and contributions are welcome
- [ ] 1. New UWP Unit Testing Template
 a. It need to package the new TestPlatform.
 b. It need to invoke the entry point in the new test platform.
- [ ] 2. Validate assumption - UWP app supports NetStandard2.0 - Test Platform has dependency on NetStandard1.5. It should just work. 
- [ ] 3. Implement UwpTestRuntimeProvider
- [ ] 4. Design & change in Test Window code to consume ITestRuntimeProvider
- [ ] 5. Migration of existing UWP UT projects to new template.
	
#### Discussions 
1. [InitializeCommunication](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/EventHandlers/TestRequestHandler.cs) will work inside a UWP Emulator, IOT Device, UWP Phone. It connects to the Tcp Server running on the vstest.console runner.
2. struct TestRunnerConnectionInfo in [ITestRuntimeProvider](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Host/ITestRunTimeProvider.cs)
 a. does it need to have IP address to support remote machine scenario?
 b. How goes logfile get transferred from host to runner - in remote machine scenario?
3. HostProviderEventArgs 
 a. Does It need to have IP address?
4. [LaunchTestHostAsync](https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.ObjectModel/Host/ITestRunTimeProvider.cs) - Should it take a CancellationToken parameter?
5. Should the cmdline take appx as input or simply the dll? 
6. Will there be one UwpTestRuntimeProvider implementation that will work with both VS test runner (test explorer) as well as vstest.console CLI runner?
6. Can we address the issue of need to import certificate of the test appx into the root certifcates for the machine prior to running UWP tests?
7. What does VS debugger need to be able to connect to process on the remote machine?
8. How does engine find & load test adapters when they are packaged inside the appx package?
9. Which repo should these be hosted? It will be good to have them on github and have the tests be part of UWP nightly test runs in the device lab to get consistent coverage on par with UWP app templates.
 a. New UWP UT template
 b. UWPTestRuntimeProvider
10. Is UWP platform preview bits with NetStandard2.0 support available that can be used to try the scenario end to end?

**Comment by sbaid** [comment]
@unniravindranathan @mayankbansal018 @codito

**Comment by pvlakshm** [comment]
Device support is enabled in 15.5 Preview 2.
