### ISSUE TITLE
vstest backlog

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/vstest#686]
## vstest backlog
Here is our [roadmap](https://github.com/Microsoft/vstest-docs/blob/master/roadmap.md). It calls out the broad themes for our work on the test platform. The below list of issues breaks that down to the line item level focus of our work aligned to the roadmap.

**Configurable CLI**
- [x] Filtering for dotnet test [#334](https://github.com/Microsoft/vstest/issues/334)
- [x] Logger extensibility [#616](https://github.com/Microsoft/vstest/issues/616), [#522](https://github.com/Microsoft/vstest/issues/522)
- [x] Console logger improvements/coloring [#639](https://github.com/Microsoft/vstest/issues/639)
**More**: We will pull in further items from this [query](https://github.com/Microsoft/vstest/issues?page=1&q=is%3Aissue+label%3A%22exp%3A+cli%22+is%3Aopen) as appropriate.

**.NET Core 2.0 support**
- [x] Add test coverage for the netcoreapp2.0: [#667](https://github.com/Microsoft/vstest/issues/667)
- [x] Add VS Unit testing templates for .NET Core 2.0: [#664](https://github.com/Microsoft/vstest/issues/664)
- [x] Enable CLI UT template for .NET core 2.0: [#666](https://github.com/Microsoft/vstest/issues/666)

**Open Editor integration** 
- [x] JSON protocol is verbose: [#396](https://github.com/Microsoft/vstest/issues/396)
- [x] JSON protocol needs versioning: [#397](https://github.com/Microsoft/vstest/issues/397)
**More**: We will pull in others from this [query](https://github.com/Microsoft/vstest/issues?q=is%3Aopen+is%3Aissue+label%3A%22exp%3A+sdk%22) as appropriate.

**Rich analysis using data collectors**
- [x] data collection support in vstest.console.exe: [#309](https://github.com/Microsoft/vstest/issues/309)
- [ ] code coverage support on .NET Core: [#579](https://github.com/Microsoft/vstest/issues/579)

**Performance**
- [x] xUnit adapter perf. in VisualStudio and vstest.console runners: [#485](https://github.com/Microsoft/vstest/issues/485)
- [x] Communication layer should use streams for JSON serialization: [#129](https://github.com/Microsoft/vstest/issues/129)
- [x] JSON protocol is verbose: [#396](https://github.com/Microsoft/vstest/issues/396)
- [ ] Evaluate data interchange constructs in test platform [#648](https://github.com/Microsoft/vstest/issues/648) 
- [x] Discovery of 10k tests should show up in chunks: [#76](https://github.com/Microsoft/vstest/issues/76)
**More**: We will continue to profile looking for bottlenecks, and pull in other items from this [query](https://github.com/Microsoft/vstest/issues?q=is%3Aissue+is%3Aopen+label%3Aperf) as appropriate.

**Extensible application platform support**
- [x] Devices support in vstest: [#684](https://github.com/Microsoft/vstest/issues/684)

**vstest onboarding for desktop projects**
- [ ]  We’re tracking this partner blocking [query](https://github.com/Microsoft/vstest/labels/blocking%20partner) for migrating customers with desktop projects.

**Comment by gulbanana** [comment]
any plan to work on improved handling of multi-TFM testing? right now, you can't write a set of tests for multitargetting projects and run it against each tfm in visual studio.

**Comment by codito** [comment]
@gulbanana MTFM support (tracked by #298) is at the top of [test explorer backlog](https://github.com/Microsoft/vstest/issues/676).

**Comment by gulbanana** [comment]
great! i didn't realise that was a separate issue :)

**Comment by roizentner** [comment]
How is #894 not on your backlog/roadmap?!
How is this issue not getting the attention it deserves? This is a major flaw that's been around since the introduction of vstest.
Now, with data-driven tests executed via VSTS, we can't be expected to rollback to the old mstest!
